app:
  name: city-populations
  replicaCount: 2
  port: 5000
  image:
    repository: ghcr.io/ahmedovelshan/city-population-app
    tag: "c94b63a"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"
elasticsearch:
  name: "elasticsearch"
  replicas: 1
  discoveryType: "single-node"
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch"
    tag: "8.15.0"
  port: 9200
  heap: "512m"
  secretName: "elasticsearch-credentials"
  persistence: true
  storageClass: ""
  storageSize: "10Gi"
  username: "elastic"
  password: "password"
  clusterName: "city-population-cluster"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
namespace:
  name: city-population-app
