image:
  repository: ghcr.io/ahmedovelshan/city-population-app
  tag: latest
  pullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

elasticsearch:
  name: "elasticsearch"
  replicas: 1
  discoveryType: "single-node"
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch"
    tag: "8.15.0"
  port: 9200
  heap: "512m"
  url: "http://elasticsearch-master:9200"
  secretName: "elasticsearch-credentials"
  storageSize: "10Gi"
  storageClass: ""
  appName: "city-population-app"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

resources: {}