# ==========================================
# APP CONFIGURATION
# ==========================================
app:
  name: city-populations
  replicaCount: 1
  port: 5000
  image:
    repository: ghcr.io/ahmedovelshan/city-population-app
    tag: "297f8ef" # or your latest image tag
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"
# ==========================================
# ELASTICSEARCH CONFIGURATION
# ==========================================
elasticsearch:
  name: "elasticsearch"
  replicas: 1
  discoveryType: "single-node"
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch"
    tag: "8.15.0"
  port: 9200
  heap: "512m"
  # Secret name used by the app and ES
  secretName: "elasticsearch-credentials"
  # Persistence (PVC)
  persistence: true
  storageClass: "" # leave empty to use default StorageClass
  storageSize: "10Gi"
  # Basic credentials (only for dev/testing)
  username: "elastic"
  password: "password"
  # Cluster settings
  clusterName: "city-population-cluster"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
# ==========================================
# NAMESPACE
# ==========================================
namespace:
  name: city-population-app
