image:
  repository: ghcr.io/ahmedovelshan/city-population-app
  tag: latest
  pullPolicy: Always
  resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
  port: 9200
  heap: 512m
  url: "http://elasticsearch-master:9200"
  username: "elastic"
  password: "password"
  resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"


resources: {}
