app:
  name: city-populations
  replicaCount: 2
  port: 5000
  image:
    repository: ghcr.io/ahmedovelshan/city-population-app
    tag: "v1.0.0"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

elasticsearch:
  name: "elasticsearch"
  replicas: 1
  discoveryType: "single-node"
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch"
    tag: "8.15.0"
  port: 9200
  heap: "512m"
  secretName: "elasticsearch-credentials"
  persistence: true             # Set to false to disable PV
  storageClass: ""              # Empty = use cluster default
  storageSize: "10Gi"
  username: ""
  password: ""
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "250m"
