name: Build and Push Docker Image

on:
  push:
    paths:
      - "app/**"
      - "helm-chart/values.yaml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag from Git SHA
        id: vars
        run: echo "IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/ahmedovelshan/city-population-app
          docker build -t $IMAGE_NAME:${{ env.IMAGE_TAG }} -t $IMAGE_NAME:latest ./app

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/ahmedovelshan/city-population-app
          docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}
          docker push $IMAGE_NAME:latest

      - name: Update values.yaml with new tag
        run: |
          TAG=${{ env.IMAGE_TAG }}
          yq e -i ".app.image.tag = \"$TAG\"" helm-chart/values.yaml
